import pandas as pd
import numpy as np


genetox2 = {'fluctuation test': 'bacterial fluctuation assay',
 'bacterial fluctuation assay':'bacterial fluctuation assay',
 'pol A+ ,pol A-assay .': 'pol_A assay',
 'pol A+ ,pol A-assay':'pol_A assay',
 'Rec assay': 'Rec assay',
 'REC and POL Assays.':'Rec assay',
 'rec-assay':'Rec assay',
 'Rec-assay, DNA effects (bacterial DNA repair)':'Rec assay',
 'Rec-assay, spot test, DNA effects (bacterial DNA repair)':'Rec assay',
 'bacterial forward mutation assay':'bacterial forward mutation assay',
 'bacterial reverse mutation test (single strain)':'bacterial reverse mutation test',
 'Mutation Other': 'Other mutation',
 'bacterial reverse mutation test':'bacterial reverse mutation test',
 'bacterial reverse mutation assay':'bacterial reverse mutation test',
 'T30-19: DNA Damage in E. Coli': 'DNA damage/repair',
 'Ames Salmonella reversion assay':'bacterial reverse mutation test',
 'Salmonella/microsome assay':'Other mutation',
 'Liquid suspension assay (Modified Salmonella/Mammalian-Microsome Mutagenicity Test (Ames Preincubation Test))':'Other mutation',
 'DNA damage in bacterial cells': 'DNA damage/repair',
 'Mutation in microorganisms':'Other mutation',
 'Ames test & SOS Chromotest':'Other mutation',
 'bacterial mutation assay':'bacterial reverse mutation test',
 'Liquid incubation assay':'Other mutation',
 'Salmonella/microsome test (Ames test) and chromosomal abberation  test in vitro':'Other mutation',
 'Mutagenic potential assey using a bacterial/microsome test system':'Other mutation',
 'Liquid Suspension Assay (Modified Salmonella/Mammalian-Microsome  Mutagenicity Test)':'Other mutation',
 'bacterial gene mutation and cell transformation':'Other mutation',
 'Salmonella/mammalian microsome test':'Other mutation',
 'Spot test':'Other mutation',
 'bacterial reversion assay, the WP2 Mutoxitest':'Other mutation',
 'bacterial reverse mutation assay (Salmonella typhimurium and Escherichia coli)':'bacterial reverse mutation test',
 'reparation test with Escherichia coli': 'Other mutation',
 'modified Ames assay':'Other mutation',
 'Modified Ames test':'Other mutation',
 'bacterial reverse mutation assay (Modified Ames test)':'bacterial reverse mutation test',
 'STANDARD PLATE':'Other mutation',
 'Saccharomyces cerevisia D7 test':'Other mutation',
 'Bacterial repair test':'Other mutation',
 'Ames test and DNA-repair test':'Other mutation',
 'bacterial mutation':'Other mutation',
 'Salmonella and Escherichia strains: bacterial reverse mutation assay (e.g. Ames test) ; Bacillus strains: recombination assay':'Other mutation',
 'Tryptophan reverse gene mutation':'Other mutation',
 'Forward and reverse gene mutation, body fluid assay':'Other mutation',
 'Forward and reverse gene mutation, mitotic recombination and gene conversion, DNA effects, chromosome aberrations, host-mediated assay':'Other',
 'Forward and reverse gene mutation, mitotic recombination and gene conversion, DNA effects, host-mediated assay': 'Other',
 'Forward and reverse gene mutation, chromosome aberrations, mitotic recombination and gene conversion, DNA effects, host-mediated assay': 'Other',
 'Ames test and Comet assay': 'Other',
 'Ames test and Comet assay (in-vitro)': 'Other',
 'Forward and reverse gene mutation, host-mediated assay':'Other mutation',
 'Forward and reverse gene mutation, lethal mutation, host-mediated assay':'Other mutation',
 'DNA damage, gene mutation, reverse mutation, gene conversion, DNA repair, chromosomal aberration, chromatid exchange, UDS' : 'DNA damage/repair',
 'bacterial reverse mutation assay and mouse lymphoma assay':'Other',
 'Ames Salmonella typhimurium AND Mouse Lymphoma cell mutation assay':'Other',
 '3 different methods: direct bacterial assay (ames test), microsomial mutagnesis assay, host mediated assay.':'Other mutation',
 'Forward and reverse gene mutation, mitotic recombination and gene conversion, DNA effects, body fluid assay':'Other mutation',
 'Forward and reverse gene mutation, mitotic recombination and gene conversion, host-mediated assay':'Other mutation',
 'Forward and reverse gene mutation, lethal mutation, mitotic recombination and gene conversion, DNA effects, host-mediated assay ':'Other mutation',
 'Forward and reverse gene mutation, lethal mutation, mitotic recombination and gene conversion, chromosome effects, DNA effects, host-mediated assay':'Other',
 'Ames, chromosome aberration, sister chromatid exchange, mouse lymphoma':'Other',
 'InVitroCA' : 'in vitro mammalian chromosome aberration test',
 'InVivoCA':'in vivo chromosome aberrations',
 'Cytotoxicity': 'cytotoxicity',
 'Evaluation of metabolic activity of acute cytotoxicity': 'cytotoxicity',
 'InVivoDNADamage': 'DNA damage/repair',
 'DNA damage/repair': 'DNA damage/repair',
 'Escherichia coli polA+/polA- assay':'pol_A assay',
 'DNA Repair Test with polA+ and polA- Mutants of Esherichia Coli':'pol_A assay',
 'DNA repair test':'DNA damage/repair',
 'yeast forward mutation and mitotic gene conversion assays in Schizosaccharomyces pombe (P1 strain) and Saccharomyces cerevisiae (D4 strain)': 'Other mutation',
 'forward mutation': 'Other mutation',
 'Forward gene mutation':'Other mutation',
 'Drosophila SLRL assay':'Drosophila sex-linked recessive lethal (SLRL) test',
 'Drosophila SLRL and reciprocal translocation tests':'Drosophila sex-linked recessive lethal (SLRL) test' ,
 'UZ test': 'Other',
 'gene mutation (plant)':'Other mutation',
 'Reverse gene mutation, host-mediated assay':'Other mutation',
 'in vitro gene mutation assay in yeast':'Other mutation',
 'gene mutation assay in fungi':'Other mutation',
 'yeast cytogenetic assay':'Other mutation',
 'Reverse mutation and mitotic gene conversion in Saccharomyces cerevisiae':'Other mutation',
 'yeast mitotic gene conversion assay':'Other mutation',
 'Gene mutation assay in yeast':'Other mutation',
 'GENE CONVERSION IN DIPLOID YEAST':'Other mutation',
 'Schizosaccharomyces pombe gene mutation assay':'Other mutation',
 'Reverse gene mutation':'Other mutation',
 'Mitotic recombination or gene conversion':'Other mutation',
 'Gene conversion, DNA effects': 'Other',
 'sex-linked recessive lethal assay': 'Drosophila sex-linked recessive lethal (SLRL) test' ,
 'Sex-linked recessive lethal gene mutation':'Drosophila sex-linked recessive lethal (SLRL) test' ,
 'Alkaline elution or Ewig and Kohn method': 'Other',
 'alkaline elution in vivo (single cell gel assay)':'Other',
 'Alkaline DNA elution test':'Other',
 'in vitro cell transformation assay': 'Other',
 'Cytogenetics Other':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration test (migrated information)':'in vitro mammalian chromosome aberration test',
 'chromosome aberration study in mammalian cells':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian chromosome aberration':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'chromosome aberration test': 'Other chromosomal aberration',
 'Chromosome Aberrations in Human Lymphocytes':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration assay':'Other chromosomal aberration',
 'In vitro mammalian chromosome aberration assay':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian Chromosomal Aberration Assay':'in vitro mammalian chromosome aberration test',
 'In vitro chromosome aberration assay':'in vitro mammalian chromosome aberration test',
 'Chromosome Aberration assay':'in vitro mammalian chromosome aberration test',
 'Chromosome aberation test in human lymphocytes (In vitro)':'in vitro mammalian chromosome aberration test',
 'In vitro Chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'in vitro chromosome aberration study':'in vitro mammalian chromosome aberration test',
 'chromosome aberration assay':'in vitro mammalian chromosome aberration test',
 'Chromosome Aberration test':'in vitro mammalian chromosome aberration test',
 'in vitro chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'chormosomal aberrations':'in vitro mammalian chromosome aberration test',
 'in vitro chromosome aberration study in mammalian cells':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian: chromosome aberration assay using Chinese hamster ovary cells': 'in vitro mammalian chromosome aberration test',
 'Chromosome aberration (clastogenic potential)':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian cytogenicity/chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosomal aberration test':'in vitro mammalian chromosome aberration test',
 'chromosome aberration':'in vitro mammalian chromosome aberration test',
 'in vitro mammallian chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'in vitro chromosome aberration':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian chromosome aberration test.':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian cell chromosome aberration assay':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration assay in mammalian cells':'in vitro mammalian chromosome aberration test',
 'In Vitro Mammalian Chromosome Aberration Test in Human Peripheral Blood Lymphocytes':'in vitro mammalian chromosome aberration test',
 'chromosomal aberration test':'in vitro mammalian chromosome aberration test',
 'chromosome aberration assay in mammalian cells':'in vitro mammalian chromosome aberration test',
 'Chromosome abberation test':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian chromosomal aberration test':'in vitro mammalian chromosome aberration test',
 'In vitro chromosomal aberration test':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosomal aberration assay':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration assay':'in vitro mammalian chromosome aberration test',
 'chromosome aberration in mammalian cells':'in vitro mammalian chromosome aberration test',
 'chromosomal aberration assay':'in vitro mammalian chromosome aberration test',
 'structural chromosome aberrations test in somatic and/or germ cells':'in vitro mammalian chromosome aberration test',
 'Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'In vitro chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'chromsome aberration':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration test chromosome aberration':'in vitro mammalian chromosome aberration test',
 'Cytogenetic Assay':'in vitro mammalian chromosome aberration test',
 'chromosomal aberrations':'in vitro mammalian chromosome aberration test',
 'in vitro cytogenicity study in mammalian cells':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian cell chromosme aberration test':'in vitro mammalian chromosome aberration test',
 'mammalian chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome abberation test':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian chromosome aberration study':'in vitro mammalian chromosome aberration test',
 'Mammalian Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'In Vitro Mammalian Chromosomal Aberration Test':'in vitro mammalian chromosome aberration test',
 'Mammalian Cells Chromosomal Aberration Test':'in vitro mammalian chromosome aberration test',
 'In vitro Chromosome Aberration Assay':'in vitro mammalian chromosome aberration test',
 'mammalian chromosome aberration assay':'in vitro mammalian chromosome aberration test',
 'mammalian chromosomal aberration test':'in vitro mammalian chromosome aberration test',
 'chromosome aberration study':'in vitro mammalian chromosome aberration test',
 'In vitro Mammalian Chromosomal Aberration Test with human lymphocytes':'in vitro mammalian chromosome aberration test',
 'In vitro Mammalian Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'in vitro chromosome aberration assay':'in vitro mammalian chromosome aberration test',
 'Chromosomal aberration':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration test in human lymphocytes in vitro':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration test in mammalian cells':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian cytogenetic test':'in vitro mammalian chromosome aberration test',
 'in vitro cytogenicity / chromosome aberration study in mammalian cells':'in vitro mammalian chromosome aberration test',
 'In vitro chromosome breakage assay':'in vitro mammalian chromosome aberration test',
 'In Vitro Chromosomal Aberration Test':'in vitro mammalian chromosome aberration test',
 'In Vitro Mammalian Chromosome Aberration study':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberation test':'in vitro mammalian chromosome aberration test',
 'chromosome aberrations':'in vitro mammalian chromosome aberration test',
 'in vitro chromosomal aberration test in cultured human lymphocyte cell culture':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration test, human lymphocytes from healthy, non-smoking donors.':'in vitro mammalian chromosome aberration test',
 'chromosomal aberration test in mammalian cells':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration test in CHO chinese ovary cells':'in vitro mammalian chromosome aberration test',
 'In vitro Chromosome Aberration Test in Chinese Hamster V79 Cells':'in vitro mammalian chromosome aberration test',
 'in vitro cytogenicity study in mammalian cells - Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'cytogenicity in mammalian cells':'in vitro mammalian chromosome aberration test',
 'Chromosomal aberration assay utilizing rat lymphocytes.':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration study':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration in chinese hamster ovary (CHO) cells':'in vitro mammalian chromosome aberration test',
 'Testing and evaluation of clastogenic potential - chromosomal aberrations assays.':'in vitro mammalian chromosome aberration test',
 'CHROMOSOMAL ABERRATIONS IN CHINESE HAMSTER OVARY (CHO) CELLS':'in vitro mammalian chromosome aberration test',
 'chromosome aberration test.':'in vitro mammalian chromosome aberration test',
 'Chromosome aberrations in cultured human lymphocytes':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian cell chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'Chromosome breakage study in vitro':'in vitro mammalian chromosome aberration test',
 'In vitro chromosome aberration in cultured peripheral human lymphocytes':'in vitro mammalian chromosome aberration test',
 'In vitro Mammalian Chromosome  Aberration Test':'in vitro mammalian chromosome aberration test',
 'chromosome aberration in peripheral human lymphocytes':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome abberation':'in vitro mammalian chromosome aberration test',
 'In vitro mammalian cells chromosome aberration':'in vitro mammalian chromosome aberration test',
 'in vitro chromosome aberration test in mammalian cells':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration test: chromosome aberration':'in vitro mammalian chromosome aberration test',
 'cytogenetic test, which detects structural chromosome aberrations in somatic and/or germ cells':'in vitro mammalian chromosome aberration test',
 'In Vitro Mammalian Chromosomal Aberration Assay in Chinese Hamster Ovary (CHO) Cells':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chromosome aberration':'in vitro mammalian chromosome aberration test',
 'In vitro chromosomal aberration assay':'in vitro mammalian chromosome aberration test',
 'in vitro mammalian chrommosome aberration test':'in vitro mammalian chromosome aberration test',
 'Chromosome Aberration Test in Human Lymphocytes in vitro':'in vitro mammalian chromosome aberration test',
 'in vitro chromosomal aberration study in mammalian cells':'in vitro mammalian chromosome aberration test',
 'in vitro cytogenetic test; in vitro mammalian chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'Cytogenetic assay.':'in vitro mammalian chromosome aberration test',
 'Chromosome Aberrations in Chinese Hamster Ovary (CHO) Cells (Cytogenetic assay)':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration  test in  human  lymphocytes':'in vitro mammalian chromosome aberration test',
 'chromosome aberration in human lymphocytes':'in vitro mammalian chromosome aberration test',
 'In vitro mammallian chromosome aberration study':'in vitro mammalian chromosome aberration test',
 'in vitro CA':'in vitro mammalian chromosome aberration test',
 'Cytogenetic assay':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration study':'in vitro mammalian chromosome aberration test',
 'mammalian cell cromosome aberration':'in vitro mammalian chromosome aberration test',
 'In vivo Mammalian Bone Marrow Cytogenetic Test – Chromosomal Analysis"': 'in vivo chromosome aberrations',
 'mammalian cell clastogenicity assay':'in vitro mammalian chromosome aberration test',
 'Chromosome aberration assay in spermatogonial cells': 'Other',
 'In vitro chromosome aberration study':'in vitro mammalian chromosome aberration test',
 'Cytogenetic study':'in vitro mammalian chromosome aberration test',
 'cytogenic assay':'in vitro mammalian chromosome aberration test',
 'cytogenetics assay':'in vitro mammalian chromosome aberration test',
 'Cytogenetic assay in bone marrow cells':'Other',
 'mammalian cell cytogenetic assay':'in vitro mammalian chromosome aberration test',
 'cytogenetic damage which results in the formation of micronuclei containing chromosome fragments or whole chromosomes.': 'Other chromosomal aberrations',
 'Chromosomal examination':'Other',
 'mammalian cell cytogenicity test':'in vitro mammalian chromosome aberration test',
 'chromosome aberrations (plant)': 'chromosome aberrations (plant)',
 'Heritable translocation test, chromosome aberrations': 'Other',
 'Chromosome aberrations, DNA effects, host-mediated assay': 'Other',
 'chromosome aberration and micronucleus formation':'in vivo micronucleus test',
 'SCE, Chromosomal aberrations and micronucleus': 'Other chromosomal aberration',
 'in vitro chromosomal aberration and in vitro micronucleus test':'Other chromosomal aberration',
 'combined chromosome aberration and micronucleus assay':'Other chromosomal aberration',
 'assays in parallel: bone marrow / spermatogonias chromosome aberration; erythrocyte micronucleus test':'Other chromosomal aberration',
 'Rat bone marrow chromosome aberration/micronucleus test':'in vivo micronucleus test',
 'mammalian erythrocyte micronucleus test':'in vivo micronucleus test',
 'other: Combination of Sister Chromatid Exchanges/Micronucleus /Chromosome Aberration on human leukocytes in vitro':'Other chromosomal aberration',
 'Combination of Sister Chromatide Exchanges/Micronucleus in vitro/Chromosome Aberration on human leukocytes in vitro':'Other chromosomal aberration',
 'Comparative cytogenetic studies: micronucleus test in mouse and hamster, chromosome aberration test in hamster, Sister Chromatid Exchange test in hamster':'Other chromosomal aberration',
 'in vitro mammalian chromosome aberration test/ sister chromatid exchange assay in mammalian cells':'Other chromosomal aberration',
 'chromosomal aberration and sister chromatid exchanges in mammalian cells':'Other chromosomal aberration',
 'Chromosomal Aberrations (ABS) and Sister Chromatid Exchanges (SCE)':'Other chromosomal aberration',
 'Sister chromatid exchange assay and chromosome aberration test in primary human lymphocytes':'Other chromosomal aberration',
 'in vitro mammalian chromosome aberration test and in vitro sister chromatid exchange':'Other chromosomal aberration',
 'in vitro mammalian chromosome aberration test and sister chromatid exchange assay in mammalian cells':'Other chromosomal aberration',
 'chromosome breakages, sister chromatid exchanges and micronuclei':'Other chromosomal aberration',
 'Mammalian Cell Chromosome Aberration and Sister Chromatid Exchange':'Other chromosomal aberration',
 'in vivo chromosome aberrations':'in vivo chromosome aberrations',
 'In-vitro Mammalian Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'In-vitro determination of chromosomal aberration frequency and incidence of polyploidy':'in vitro mammalian chromosome aberration test',
 'In-vitro chromosomal aberration assay utilizing rat lymphocytes.':'in vitro mammalian chromosome aberration test',
 'mammalian germ cell cytogenetic assay':'in vitro mammalian chromosome aberration test',
 'mammalian bone marrow chromosome aberration test (migrated information)':'in vivo chromosome aberrations',
 'mammalian bone marrow chromosome aberration test':'in vivo chromosome aberrations',
 'mouse spermatogonia chromosomal aberration test':'in vivo chromosome aberrations',
 'Mammalian somatic cell cytogenetic assay':'in vitro mammalian chromosome aberration test',
 'Bone marrow chromosome aberration test':'in vivo chromosome aberrations',
 'In vivo chromosome aberration assay':'in vivo chromosome aberrations',
 'Bone Marrow Abberation Test':'in vivo chromosome aberrations',
 'bone marrow chromosome aberration':'in vivo chromosome aberrations',
 'Cytogenicity / bone marrow chromosome aberration':'in vivo chromosome aberrations',
 'in vivo chromosome aberration test':'in vivo chromosome aberrations',
 'In vivo mammalian bone marrow chromosome aberration assay':'in vivo chromosome aberrations',
 'In vivo mammalian chromosome aberration assay':'in vivo chromosome aberrations',
 'In vivo mammalian chromosome aberration study':'in vivo chromosome aberrations',
 'bone marrow chromosome aberration assay and mammalian germ cell cytogenetic assay':'in vivo chromosome aberrations',
 'Chromosome Aberrations, Sister Chromatid Exchanges and Micronuclei':'Other chromosomal aberration',
 'mammalian bone marrow cytogenetic assay':'in vivo chromosome aberrations',
 'Mammalian somatic cell cytogenicity/aneugenicity assay':'in vitro mammalian chromosome aberration test',
 'Crhomosome aberration assay':'Other chromosomal aberration',
 'Bone Marrow Chromosomal Aberration':'in vivo chromosome aberrations',
 'mammalian somatic cell cytogenicity assay':'in vitro mammalian chromosome aberration test',
 'Mammalian bone marrow chromosome aberrration test': 'in vivo chromosome aberrations',
 'DNA Covalent Binding' : 'DNA damage/repair',
 'DNA adduct formation':'DNA damage/repair',
 'DNA Binding':'DNA damage/repair',
 'comet assay':'DNA damage/repair',
 'Comet assay on plant cells (Nicotiana tabacum)':'DNA damage/repair',
 'Comet assay':'DNA damage/repair',
 'COMET assay':'DNA damage/repair',
 'mammalian comet assay':'DNA damage/repair',
 'In Vivo Alkaline Comet':'DNA damage/repair',
 'comet assay.':'DNA damage/repair',
 'in vivo comet (mouse)':'DNA damage/repair',
 'in vivo comet (rat)':'DNA damage/repair',
 'DNA synthesis and repair assay':'DNA damage/repair',
 'DNA repair assays':'DNA damage/repair',
 'In Vitro Rat Hepatocyte Primary Culture/ DNA Repair Assays':'DNA damage/repair',
 'hepatocyte/DNA repair test':'DNA damage/repair',
 'E. coli K-12 DNA repair host-mediated assay':'DNA damage/repair',
 'In Vivo/ In Vitro Rat Hepatocyte Primary Culture/ DNA Repair Assays':'DNA damage/repair',
 'HPC/DN repair assay':'DNA damage/repair',
 'Mouse Lymphoma Forward Mutation Assay': 'Other mutation',
 'in vitro mammalian cell forward mutation test': 'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'CHO/HGPRT forward mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'gene mutation test at HGPRT locus':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Mammalian cell forward gene mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'CHO/HGPRT assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'forward gene mutation assay in mammalian cells':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian cell forward mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Chinese hamster ovary cells/hypoxanthine-guanine phosphoribosyl transferase (CHO/HGPRT) mutation assay was conducted for the test chemical':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In vitro Mammalian Cell Gene Forward Mutation Test':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'HGPRT assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian cells forward mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian cell gene mutation test using the Hprt and xprt genes':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 '(CHO/HGPRT) forward gene mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Chinese hamster lung cells (V79) forward mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian forward gene mutation':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'HGPRT':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian forward mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 '"In vitro Mammalian Cell Gene Mutation Tests", forward gene mutation':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Chinese hamster ovary cell (CHO –K1)':'Other mutation',
 'in vitro mammalian cell forward gene mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'forward mutations at the thymidine kinase (TK) locus in L5178Y mouse lymphoma cells': 'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'CHO/HGPRT Assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'HPRT forward mutation in mammalian cells':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In vitro mammalian cell forward mutation assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Mutagenicity Testing in the in vitro CHO/HGPRT Mutation Assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian forward mutation assay (mouse lymphoma assay)':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro mammalian cell gene mutation test using the thymidine kinase gene':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'Forward gene mutation, host-mediated assay': 'Other mutation',
 'Inhibition of gap-junctional communication':'Other mutation',
 'Mutation':'Other mutation',
 'InVitroMLA':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro mammalian cell gene mutation test':'in vitro mammalian cell gene mutation test',
 'in vitro mammalian cell gene mutation tests using the thymidine kinase gene': 'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'mouse lymphoma L5178Y cells':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro Mammalian Cell Gene mutation Test':'in vitro mammalian cell gene mutation test',
 'In Vitro Mammalian Cell Gene Mutation Test':'in vitro mammalian cell gene mutation test',
 'gene mutation in mammalian cells':'in vitro mammalian cell gene mutation test',
 'in vitro gene mutation study in mammalian cells':'in vitro mammalian cell gene mutation test',
 'in vitro mammalian cell mutation assay':'in vitro mammalian cell gene mutation test',
 'mammalian gene mutation assay (HPRT)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Mouse Lymphoma cell mutagenesis (MLY) Assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro mammalian cell gene mutation test using the Hprt and xprt genes (migrated information)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In vitro mammalian cell gene mutation assay':'in vitro mammalian cell gene mutation test',
 'Mouse lymphoma mutagenesis assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro mammalian gene mutation assay':'in vitro mammalian cell gene mutation test',
 'gene mutation assay in mammalian cells':'in vitro mammalian cell gene mutation test',
 'mammalian cell mutation assay':'in vitro mammalian cell gene mutation test',
 'HPRT':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'mammalian gene mutation assay in vitro':'in vitro mammalian cell gene mutation test',
 'in vitro mammalian cell gene mutation tests using the thymidine kinase gene (migrated information)':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro gene mutation study in mamalian cells':'in vitro mammalian cell gene mutation test',
 'In Vitro Mammalian Cell Gene Mutation Test Using the Thymidine Kinase Gene':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'Mammalian cell gene mutation test':'in vitro mammalian cell gene mutation test',
 'in vitro gene mutation study in mammalian cells (HPRT)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'L5178Y TK +/- Mouse Lymphoma Assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro Mammalian Cell Gene Mutation Test':'in vitro mammalian cell gene mutation test',
 'mammalian cell gene mutation test':'in vitro mammalian cell gene mutation test',
 'Assessing specific locus mutations at the TK locus in cultured L5178Y TK+/- Mouse Lymphoma cells.':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'induction of point mutation at HPRT-locus':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'L5178Y TK+/- mouse lymphoma mutation assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro Mammalian cell gene mutation assay.':'in vitro mammalian cell gene mutation test',
 'Mammalian cell gene mutation study':'in vitro mammalian cell gene mutation test',
 'in vitro mammalian cell gene mutation tests using the hprt and/or xprt genes':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian cell gene mutation assay (HPRT)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'L5178Y/TK+/- Mouse Lymphoma Assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in-vitro mammalian cell gene mutation assay':'in vitro mammalian cell gene mutation test',
 'HPRT test':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'mutagenicity in mammalian cells':'in vitro mammalian cell gene mutation test',
 'mammalian cell gene mutation assay (HPRT assay)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In Vitro Mammalian Cell Gene Mutation Test (tk locus)':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'HPRT Locus assay in mammalian cells':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian mutation study':'in vitro mammalian cell gene mutation test',
 'In vitro mammalian gene mutation assay using the Hprt gene.':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Mutation assay at the thymidine kinase locus in L5178Y mouse lymphoma cells':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'mouse lymphoma test':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro Mammalian Cell Gene Mutation Tests"':'in vitro mammalian cell gene mutation test',
 'Test de mutation de gène de cellules mammaliènnes':'in vitro mammalian cell gene mutation test',
 'Gene mutations at the hypoxanthine-guanine phosphoribosyl transferase (HPRT) locus in Chinese hamster ovary (CHO) cells in vitro.':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Mammalian Cell Gene Mutation Test with L5178Y Mouse Lymphoma Cells':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'Mammalian cell gene (Mouse lymphoma  TK +/- assays)':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'Mouse Lymphoma Mutagenicity Assay.':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In Vitro Mammalian Cell Gene Mutation Test (HPRT)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'mammalian cell gene mutation':'in vitro mammalian cell gene mutation test',
 'In vitro Mammalian cell gene mutation test using the Hprt Gene':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes' ,
 'in vitro gene mutation in mammalian cells':'in vitro mammalian cell gene mutation test',
 'mouse lymphoma TK+/- assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'Mouse Lymphoma':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'HPRT mutation system in Chinese hamster V79 cells':'in vitro mammalian cell gene mutation test',
 'mammalian cell gene mutation in vitro':'in vitro mammalian cell gene mutation test',
 'In Vitro Mammalian Cell Gene Mutation Test With L5178y Mouse Lymphoma Cells':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'BlueScreen HC Assay': 'Other',
 'In Vitro Mammalian Cell Gene Mutation Test using the Hprt genes following OECD 476':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro mammalian cell mutation study':'in vitro mammalian cell gene mutation test',
 'Mammalian gene mutation study':'in vitro mammalian cell gene mutation test',
 'HPRT Assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Gene Mutation Assay in Mammalian Cells in vitro (HPRT)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In-Vitro Gene Mutation study in Mammalian Cells':'in vitro mammalian cell gene mutation test',
 'In vitro mammalian gene mutaation study':'in vitro mammalian cell gene mutation test',
 'in vitro HPRT test':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In Vitro Mammalian Cell Gene Mutation Tests using the Hprt and xprt genes':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In Vitro Mammalian Gene Mutation Assay':'in vitro mammalian cell gene mutation test',
 'HPRT-Test':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In Vitro Mammalian Cell Gene Mutation Test (Chinese hamster V79 HPRT-assay)':'in vitro mammalian cell gene mutation test',
 'L5178Y TK +1- Mouse Lymphoma Assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'Mammalian Cell Gene Mutation Test Using the Thymidine Kinase Gene':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro mammalian cell gene mutation test.':'in vitro mammalian cell gene mutation test',
 'In vitro Mammalian Cell Gene Mutation Assay in Mouse Lymphoma L5178Y Cells':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'mammalian cell  gene mutation assay':'in vitro mammalian cell gene mutation test',
 'mammalina cell gene mutation assay':'in vitro mammalian cell gene mutation test',
 'in vitro mammalian cell gene mutation test with L5178Y mouse lymphoma cells.':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro gene mutation mammalian cell assay.':'in vitro mammalian cell gene mutation test',
 'in vitro gene mutation test in mammalian cells':'in vitro mammalian cell gene mutation test',
 'gene mutation assay in mammalian cells in vitro':'in vitro mammalian cell gene mutation test',
 'in vitro mammalian gene mutation':'in vitro mammalian cell gene mutation test',
 'in vitro mammalian gene mutation assay (HPRT)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In vitro mammalian cell gene mutation in Chinese Hamster V79 Cells':'in vitro mammalian cell gene mutation test',
 'gene mutation study in mammallian cells':'in vitro mammalian cell gene mutation test',
 'Syrian hamster embryo (SHE) cells': 'Other',
 'gene mutation in mammalian cells using the thymidine kinase locus':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro gene mutation assay  in mammalian cells':'in vitro mammalian cell gene mutation test',
 'mammalian cell gene mutation test (HPRT assay)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'mammalian gene mutation test':'in vitro mammalian cell gene mutation test',
 ': In Vitro L5178Y Gene Mutation Assay at the hprt locus':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'V79 HPRT Gene Mutation Assay':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'In vitro mammalian cell gene mutation test (HPRT)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'in vitro gene mutation study in mammalian cells (Mouse lymphoma assay)':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'L5178 mouse lymphoma  cells (HPRT)':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'L5178Y TK mouse lymphoma mutagenesis assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro mammalian cell gene mutation test using the Hprt gene':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'gene mutation study in mammalian cells':'in vitro mammalian cell gene mutation test',
 'Assess the potential mutagenicity of the test material on the thymidine kinase, TK +/-, locus of the L5178Y mouse lymphoma cell line.':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'Mammalian-Microsome Mutagenicity Assay': 'Other mutation',
 'In vitro Mammalian Cell Gene Mutation Tests using the Hprt and xprt genes':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'Mammalian Cell  Gene Mutation Test with L5178Y Mouse Lymphoma Cells':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'BlueScreen HC assay': 'Other',
 'The Chinese Hamster Ovary (CHO) Mutation test':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'mause Iymphoma L5178Y TK assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro mamammlian cell gene mutation tests using the thymidine kinase gene':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'L5178Y mouse lymphoma cell mutation assays':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'HPRT assay in Chinese Hamster V79 cells':'in vitro mammalian cell gene mutation test',
 'in vitro mammalian cell mutation test - Mouse Lymphoma Assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro gene mutation test in CHO cells (HPRT locus assay)':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'mammalian cell gene mutation assay: gene mutation':'in vitro mammalian cell gene mutation test',
 'In vitro mammlian cell mutation':'in vitro mammalian cell gene mutation test',
 'In Vitro Mammalian Cell Gene Mutation Test using the Hprt gene':'in vitro mammalian cell gene mutation test using the Hprt and xprt genes',
 'mammalian gene mutation assay':'in vitro mammalian cell gene mutation test',
 'In vitro mammalian cell  gene mutation assay':'in vitro mammalian cell gene mutation test',
 'in vitro gene mutation in mammalian cells (Mouse lymphoma assay)':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro Mammalian Cell Gene Mutation Test (Mouse Lymphoma Assay)':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro mammalian cell gene mutation.':'in vitro mammalian cell gene mutation test',
 'In vitro gene mutation test in mammalian cells':'in vitro mammalian cell gene mutation test',
 'mouse lymphoma thymidine kinase assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro DNA mutation':'Other mutation',
 'mouse lymphoma thymidine kinase locus assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in-vitro mammalian gene mutation assay':'in vitro mammalian cell gene mutation test',
 'Mammalian Cell Gene Mutation Test with L5178Y Mouse Lymphoma Cells.':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'transgenic rodent mutagenicity assay':'transgenic rodent somatic and germ cell gene mutation assays (TGR)',
 'ex vivo HPRT assay':'Other mutation',
 'Spot test, gene mutation': 'Other mutation',
 'Specific locus test, gene mutation': 'Other mutation',
 '1. mammalian cell gene mutation assay, 2. sister chromatid exchange assay in mammalian cells in vitro DNA damage and/or repair study':'Other',
 'rodent dominant lethal assay':'rodent dominant lethal assay',
 'dominant lethal assay':'rodent dominant lethal assay',
 'Dominant Lethal Mutagenicity test': 'rodent dominant lethal assay',
 'Dominant lethal and heritable translocation studies in male mice.':'rodent dominant lethal assay',
 'fluorimetric analysis of DNA unwinding (FADU) assay and dominant lethal assay':'rodent dominant lethal assay',
 'Dominant lethal test':'rodent dominant lethal assay',
 'heritable translocation assay': 'Other',
 'Metaphase analysis in CHO cells':'Other',
 'in vitro mammalian cell micronucleus test':'in vitro mammalian cell micronucleus test',
 'In vitro micronucleus test':'in vitro mammalian cell micronucleus test',
 'In vitro Micronucleus test':'in vitro mammalian cell micronucleus test',
 'in vivo dosing + MN (micronuclei)':'in vivo micronucleus test',
 'Gene Mutation-Micronucleus Combination Assay Of Diallyl Phthalate In Muta Mouse': 'Other',
 'bone marrow micronucleus test': 'in vivo micronucleus test',
 'Erythrocyte Micronucleus Assay': 'in vivo micronucleus test',
 'In vitro mammalian micronucleus assay':'in vitro mammalian cell micronucleus test',
 'Bone marrow (Mammalian Erythrocyte) Micronucleus Test': 'in vivo micronucleus test',
 'cytogenicity / erythrocyte micronucleus test': 'in vivo micronucleus test',
 'Erythrocyte micronucleus assay': 'in vivo micronucleus test',
 'Gastrointestinal tract MN micronucleus (MN) assays':'in vitro mammalian chromosome aberration test',
 'in vitro micronucleus': 'in vivo micronucleus test',
 'in vivo micronucleus test': 'in vivo micronucleus test',
 'in vivo micronucleus assay': 'in vivo micronucleus test',
 'cytokinesis-block micronucleus assay':'in vitro mammalian chromosome aberration test',
 'micronucleustest in vitro on human lymphocytes':'in vitro mammalian chromosome aberration test',
 'micronucleus assay Type of genotoxicity: chromosome aberration': 'in vivo micronucleus test',
 'Mammalian Erythrocyte Micronucleus Test': 'in vivo micronucleus test',
 'in vivo mammalian somatic cell study: cytogenicity / erythrocyte micronucleus': 'in vivo micronucleus test',
 'in vivo mouse micronucleus': 'in vivo micronucleus test',
 'Mouse bone marrow micronucleus test': 'in vivo micronucleus test',
 'mammalian erythrocyte micronucleus test (migrated information)': 'in vivo micronucleus test',
 'in vivo mammalian somatic cell study: bone marrow micronucleus': 'in vivo micronucleus test',
 'In vivo mouse micronucleus assay': 'in vivo micronucleus test',
 'Mouse MN test OECD 474': 'in vivo micronucleus test',
 'peripheral blood samples in mammalian erythrocytes micronucleus assay': 'in vivo micronucleus test',
 'Mouse bone marrow micronucleus assay': 'in vivo micronucleus test',
 'Mammalian erythrocyte micronucleus test': 'in vivo micronucleus test',
 'Mouse micronucleus study': 'in vivo micronucleus test',
 'Micronucleus assay in mice': 'in vivo micronucleus test',
 'micronucleus assay in vivo': 'in vivo micronucleus test',
 'Mouse micronucleus assay': 'in vivo micronucleus test',
 'In Vivo Micronucleus Test in Mice': 'in vivo micronucleus test',
 'In vivo bone marrow micronucleus assay': 'in vivo micronucleus test',
 'Nucleus Anomaly Test (Mikronucleus Assay)': 'in vivo micronucleus test',
 'micronucleus test': 'in vivo micronucleus test',
 'in vivo bone marrow mouse micronucleus': 'in vivo micronucleus test',
 'peripheral blood micronucleus test': 'in vivo micronucleus test',
 'In vivo micronucleus test': 'in vivo micronucleus test',
 'mouse micronucleus': 'in vivo micronucleus test',
 'Mammalian vivo Micronucleus Test': 'in vivo micronucleus test',
 'Mouse micronucleus cytogenetic assay': 'in vivo micronucleus test',
 'In Vivo Micronucleus Assay': 'in vivo micronucleus test',
 'Mammalian Erythrocyte Micronucleus Test.': 'in vivo micronucleus test',
 'in vivo mammalian bone marrow micronucleus assay': 'in vivo micronucleus test',
 'In vivo Mammalian Erythrocytes Micronucleus Test': 'in vivo micronucleus test',
 'in vivo micronucleus study': 'in vivo micronucleus test',
 'mammalian soma cell micronucleus assay':'in vitro mammalian cell micronucleus test',
 'micronucleus assay (chromosome aberration)': 'in vivo micronucleus test',
 'in vivo micronucleus test in mice': 'in vivo micronucleus test',
 'Micronucleus assay on mouse bone marrow': 'in vivo micronucleus test',
 'Mammalian bone marrow erythrocyte micronucleus test': 'in vivo micronucleus test',
 'Micronucleus test': 'in vivo micronucleus test',
 'in vivo micronucleus test : limit dose test': 'in vivo micronucleus test',
 'in vivo micronucleus test, limit dose test': 'in vivo micronucleus test',
 'in vivo micronucleus test  in the mouse': 'in vivo micronucleus test',
 'In vivo micronucleus assay': 'in vivo micronucleus test',
 'In vivo micronucleus test.': 'in vivo micronucleus test',
 'mammalianerythrocyte micronucleus test': 'in vivo micronucleus test',
 'Micronucleus assay in bone marrow cells': 'in vivo micronucleus test',
 'Mouse peripheral blood micronucleus test': 'in vivo micronucleus test',
 'Rat bone marrow micronucleus assay': 'in vivo micronucleus test',
 'The rodent bone marrow erythrocyte micronucleus (MN) assay': 'in vivo micronucleus test',
 'In vivo mammalian somatic cell study: Micronucleus study': 'in vivo micronucleus test',
 'peripheral blood and bone marow micronucleus test': 'in vivo micronucleus test',
 'In vivo rats micronucleus assay': 'in vivo micronucleus test',
 'Liver and bone marrow micronucleus assay': 'in vivo micronucleus test',
 'Repeated-dose liver micronucleus (RDLMN) assay': 'in vivo micronucleus test',
 'in vivo mammalian erythrocyte (somatic cell) micronucleus test':'in vivo micronucleus test',
 'Micronucleus assay in bone marrow': 'in vivo micronucleus test',
 'micronucleus test in vivo': 'in vivo micronucleus test',
 'Mammalian Erytrocyte Micronucleous Test': 'in vivo micronucleus test',
 'micronucleus and comet assay': 'in vivo micronucleus test',
 'in vivo MNT': 'in vivo micronucleus test',
 'RODENT BONE MARROW MICRONUCLEUS ASSAY': 'in vivo micronucleus test',
 'Micronucleus Test': 'in vivo micronucleus test',
 'Nucleus Anomaly Test':'Other',
 'Micronucleus induction': 'Other mutation',
 'In vivo Mammalian erythrocyte micronucleus assay.': 'in vivo micronucleus test',
 'in vivo micronucleus (mouse)': 'in vivo micronucleus test',
 'in vivo micronucleus (rat)': 'in vivo micronucleus test',
 'combined micronucleus and comet assay': 'in vivo micronucleus test',
 'Micronucleus and sister chromatid exchange':'Other',
 'Morphologic transformation of cells in culture':'Other',
 'In Vitro Mouse Lymphoma (L5178Y TK+/-) Mutation':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'in vitro mouse lymphoma (L5178Y/TK+/-) mutation assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In Vivo Mammalian Mutagenesis': 'Other mutation',
 'in vivo mammalian somatic cell study':'Other',
 'In vivo Mammalian Somatic cell study.':'Other',
 'sister chromatid exchange assay in mammalian cells':'Other',
 'in vitro sister chromatid exchange assay':'Other',
 'Sister chromatid exchange and chromosome abberrations':'Other',
 'sister chromatid exchange assay':'Other',
 'Sister-chromatid exchange (SCE) in vitro':'Other',
 'Sister-chromatid exchange (SCE) in vivo':'Other',
 'somatic mutation assay (Chinese hamster)':'Other',
 'somatic mutation assay':'Other',
 'Sperm abnormality assay':'Other',
 'Sperm morphology':'Other',
 'mouse spot test':'Other',
 'cell transformation':'Other',
 'cell transformation assay':'Other',
 'Cellular transformation assay':'Other',
 'mammalian cell transformation assay':'Other',
 'Cell Transformation assay':'Other',
 'Cell transformation assay':'Other',
 'Cell transformation, clonal assay':'Other',
 'Cell transformation, viral enhanced':'Other',
 'Cell transformation, focus assay' :'Other',
 'unscheduled DNA synthesis (UDS) in vitro':'DNA damage/repair',
 'Unscheduled DNA synthesis (UDS)':'DNA damage/repair',
 'Unscheduled DNA synthesis in primary hepatocyte cultures':'DNA damage/repair',
 'DNA damage and repair assay':'DNA damage/repair',
 'Unscheduled DNA synthesis in mammalian cells in vitro':'DNA damage/repair',
 'unscheduled DNA synthesis (UDS) in vivo':'DNA damage/repair',
 'In Vitro Rat Primary Hepatocyte Unscheduled DNA Synthesis (UDS) Assay':'DNA damage/repair',
 'DNA Damage and Repair/ Unscheduled DNA Synthesis in Mammalian Cells in vitro':'DNA damage/repair',
 'In vitro unscheduled DNA synthesis in mammalian cells':'DNA damage/repair',
 'Primary Rat Hepatocyte Unscheduled DNA Synthesis Assay':'DNA damage/repair',
 'unscheduled DNA Synthesis':'DNA damage/repair',
 'Unscheduled DNA Assay':'DNA damage/repair',
 'unscheduled DNA synthesis assay':'DNA damage/repair',
 'unscheduled DNA synthesis (UDS)':'DNA damage/repair',
 'unscheduled DNA synthesis (UDS), in vitro DNA damagae and/or repair study':'DNA damage/repair',
 'Induction of unscheduled DNA synthesis in primary rat hepatocytes':'DNA damage/repair',
 'Unscheduled DNA Sysnthesis':'DNA damage/repair',
 'Rat primary hepatocyte unscheduled DNA synthesis (UDS) assay':'DNA damage/repair',
 'in vitro UDS assay':'DNA damage/repair',
 'DNA damage and repair assay, unscheduled DNA synthesis in rat hepatocytes in vitro':'DNA damage/repair',
 'Sasaki et al. (1989) and Jansson et al. (1988) report on Sister Chromatid Exchanges.  Heck et al. (1989) reports on Unscheduled DNA Synthesis.  Finally, Demir et al. (2010) reports on gross DNA damage as represented by the Comet assay.': 'DNA damage/repair',
 'InVivoUDS':'DNA damage/repair',
 'unscheduled DNA synthesis':'DNA damage/repair',
 'Cell proliferation (DNA synthesis) assays':'DNA damage/repair',
 'bacteriophage induction in E. coli, gene mutation, UDS in mammalian cells, sex-linked recessive lethal mutations in Drosophila':'DNA damage/repair',
 'assay for induction of Unscheduled DNA Synthesis (UDS) in rat liver cells.':'DNA damage/repair',
 'Aneuploidy, chromosome aberrations':'Other chromosomal aberration',
 'InVitroMN':'in vitro mammalian cell micronucleus test',
 'InVivoMN':'in vivo micronucleus test',
 'mitotic recombination assay with Saccharomyces cerevisiae':'Other',
 'Mitotic recombination': 'Other',
 'In Vivo Non-mammalian Mutagenesis': 'Other mutation',
 'transgenic':'transgenic rodent somatic and germ cell gene mutation assays (TGR)',
 'Overall': 'Other',
 'genotoxic effect': 'Other',
 'In Vitro Mammalian Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'Mammalian cell gene mutation assay': 'in vitro mammalian cell gene mutation test',
 'In vitro mammalian cell assay':'Other',
 'Chinese Hamster Fibroblast cell line (CHL)':'in vitro mammalian chromosome aberration test',
 'In vitro Mammalian chromosome aberration test':'in vitro mammalian chromosome aberration test',
 'thymidine kinase locus':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 np.nan : np.nan,
 'mouse lymphoma forward mutation assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'Mouse Lymphoma Assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'IN VITRO MAMMALIAN CELL GENE MUTATION TEST':'in vitro mammalian cell gene mutation test',
 'mouse lymphoma assay':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'chromosome aberrations in human lymphocytes':'in vitro mammalian chromosome aberration test',
 'In Vitro Mammalian Cell Gene Mutation Tests Using the Thymidine Kinase Gene': 'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'see principles of method below': 'Other',
 'In vitro assay to detect inhibitors of intracellular communication': 'Other',
 'In-Vitro Mammalian Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'in vitro Mammalian Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'HGPRT Assay':'in vitro mammalian cell gene mutation test',
 'In VItro Chromosome Aberration Assay':'in vitro mammalian chromosome aberration test',
 'In Vitro Mammalian Cell Gene Mutation Test using the Thymidine Kinase Gene':'in vitro mammalian cell gene mutation test using the thymidine kinase gene',
 'In vitro gene mutation study in mammalian cells':'in vitro mammalian cell gene mutation test',
 'in vitro Mammalian Cell Gene Mutation Test':'in vitro mammalian cell gene mutation test',
 'in vitro Mammalian cell Gene Mutation Test':'in vitro mammalian cell gene mutation test',
 'Point mutations':'Other',
 'Mammalian Cell Gene Mutation Assay':'in vitro mammalian cell gene mutation test',
 'IN VITRO MAMMALIAN CHROMOSOME ABERRATION TEST':'in vitro mammalian chromosome aberration test',
 'not specified':'Other',
 'In Vitro Chromosome Aberration Test':'in vitro mammalian chromosome aberration test',
 'Gene mutation in mammalian cells':'in vitro mammalian cell gene mutation test',
 'In vitro mammalian cell gene mutation assay (HPRT)':'in vitro mammalian cell gene mutation test',
 'In vitro Mammalian Chromosomal Aberration Test':'in vitro mammalian chromosome aberration test',
 'Human Lymphocytes in vitro':'in vitro mammalian cell gene mutation test',
 'modified Ames test': 'Other mutation',
 'In vitro Mammalian Cell Gene Mutation Assay':'in vitro mammalian cell gene mutation test',
 'in vitro Mammalian Cell Gene Mutation Assay':'in vitro mammalian cell gene mutation test',
 'A cytogenetic assay in mammalian somatic cells for detection of structural chromosome aberrations using metaphase analysis.':'in vitro mammalian chromosome aberration test',
 'HPRT assay':'in vitro mammalian cell gene mutation test',
 'mammalian Tumor test':'Other',
 'No data available':'Other',
 'In vitro mammalian cell gene mutation':'in vitro mammalian cell gene mutation test',
 'in vitro Chromosome Aberration Assay':'in vitro mammalian chromosome aberration test',
 'Chromosomal Aberration Assay': 'Other chromosomal aberration',
 'Allium cepa root cells':'Other',
 'in vitro mammalian cell gene mutation test (HPRT)':'in vitro mammalian cell gene mutation test',
 'In Vitro Mammalian Cell Gene Mutation':'in vitro mammalian cell gene mutation test',
 'cultured human lymphocytes':'in vitro mammalian cell gene mutation test',
 'unspecified':'Other',
 'endogenous gene animal assay':'Other',
 'combined repeated dose and carcinogenicity':'Other',
 'Micronucleus assay':'in vivo micronucleus test',
 'Micronucleus Assay':'in vivo micronucleus test',
 'Mammalian Erythrocyte Micronucleus test':'in vivo micronucleus test',
 'Nucleoid Sedimentation Analysis Assay':'Other',
 'Repeated-dose bone marrow/peripheral blood (BM/PB) assay':'in vivo micronucleus test',
 'Non-bacteriological test in vivo - 6th amendment data':'Other',
 'Host mediated assay': 'Other',
 'Iodide accumulation studies': 'Other',
 'Single-cell gel electrophoresis':'Other',
 'mouse micronucleus assay':'in vivo micronucleus test',
 'In vivo carcinogenicity studies': 'Other',
 'Drosophila Reciprocal Translocation test':'Drosophila sex-linked recessive lethal (SLRL) test',
 'Bacillus subtilis recombination assay':'DNA damage/repair',
 'Bacillus subtilis DNA-repair test (Rec asssay)':'DNA damage/repair',
 'Drosophila somatic mutation and recombination test (SMART) and in vivo cytogenetics in rat bone marrow':'Other',
 'somatic mutation and recombination test in Drosophila':'Other',
 'Wing somatic mutation and recombination tests (SMART)':'Other',
 'Aneuploidy, partial sex chromosome loss, chromosome aberrations ':'Other chromosomal aberration',
 'Aneuploidy, sex chromosome gain, chromosome aberrations':'Other chromosomal aberration',
 'Aneuploidy, whole sex chromosome loss, chromosome aberrations': 'Other chromosomal aberration',
 'SOS/umu assay': 'Other',
 'SOS chromotest, Ames fluctuation test and newt micronucleus test': 'Other',
 'SOS chromotest, Ames fluctuation test and new micronucleus test':'Other'}
 
 
 
def clean_up2(df):
    df['standard_assay_type'].replace(genetox2 , inplace = True)
    return df
